#!/bin/bash
# Kernel build configuration
# Source this file, don't execute it

KERNEL_GIT_URL="https://github.com/rockchip-linux/kernel.git"
KERNEL_DIR_NAME="rockchip-kernel"

ARCH="arm64"
CROSS_COMPILE="aarch64-linux-gnu-"

# Profile definitions with CONFIG fragments
declare -A KERNEL_PROFILES=(
  [basic]=""
  [basic-devel]="CONFIG_DEBUG_INFO=y CONFIG_DEBUG_KERNEL=y"
  [extended]="CONFIG_BRIDGE=y CONFIG_VETH=y CONFIG_OVERLAY_FS=y CONFIG_MACVLAN=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y CONFIG_NF_NAT=y CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y CONFIG_IP_NF_NAT=y CONFIG_IP_NF_TARGET_MASQUERADE=y CONFIG_CGROUP_DEVICE=y CONFIG_CGROUP_CPUACCT=y CONFIG_CGROUP_PIDS=y CONFIG_CGROUP_FREEZER=y CONFIG_MEMCG=y CONFIG_BLK_CGROUP=y CONFIG_CGROUP_SCHED=y CONFIG_CFS_BANDWIDTH=y CONFIG_USER_NS=y CONFIG_NET_NS=y CONFIG_PID_NS=y CONFIG_IPC_NS=y CONFIG_UTS_NS=y CONFIG_SECCOMP=y CONFIG_VIRTIO=y CONFIG_VIRTIO_PCI=y CONFIG_VIRTIO_MMIO=y CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y CONFIG_VIRTIO_BLK=y CONFIG_VIRTIO_NET=y CONFIG_VIRTIO_CONSOLE=y CONFIG_HW_RANDOM_VIRTIO=y CONFIG_VIRTIO_BALLOON=y CONFIG_VIRTIO_INPUT=y CONFIG_DRM_VIRTIO_GPU=y CONFIG_SERIAL_AMBA_PL011=y CONFIG_SERIAL_AMBA_PL011_CONSOLE=y CONFIG_RTC_DRV_PL031=y CONFIG_KVM=y CONFIG_VHOST_NET=y CONFIG_VHOST=y CONFIG_VHOST_VSOCK=y CONFIG_VHOST_SCSI=y"
  [extended-devel]="CONFIG_BRIDGE=y CONFIG_VETH=y CONFIG_OVERLAY_FS=y CONFIG_MACVLAN=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y CONFIG_NF_NAT=y CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y CONFIG_IP_NF_NAT=y CONFIG_IP_NF_TARGET_MASQUERADE=y CONFIG_CGROUP_DEVICE=y CONFIG_CGROUP_CPUACCT=y CONFIG_CGROUP_PIDS=y CONFIG_CGROUP_FREEZER=y CONFIG_MEMCG=y CONFIG_BLK_CGROUP=y CONFIG_CGROUP_SCHED=y CONFIG_CFS_BANDWIDTH=y CONFIG_USER_NS=y CONFIG_NET_NS=y CONFIG_PID_NS=y CONFIG_IPC_NS=y CONFIG_UTS_NS=y CONFIG_SECCOMP=y CONFIG_VIRTIO=y CONFIG_VIRTIO_PCI=y CONFIG_VIRTIO_MMIO=y CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y CONFIG_VIRTIO_BLK=y CONFIG_VIRTIO_NET=y CONFIG_VIRTIO_CONSOLE=y CONFIG_HW_RANDOM_VIRTIO=y CONFIG_VIRTIO_BALLOON=y CONFIG_VIRTIO_INPUT=y CONFIG_DRM_VIRTIO_GPU=y CONFIG_SERIAL_AMBA_PL011=y CONFIG_SERIAL_AMBA_PL011_CONSOLE=y CONFIG_RTC_DRV_PL031=y CONFIG_KVM=y CONFIG_VHOST_NET=y CONFIG_VHOST=y CONFIG_VHOST_VSOCK=y CONFIG_VHOST_SCSI=y CONFIG_DEBUG_INFO=y CONFIG_DEBUG_KERNEL=y"
)

# Version-specific settings
get_kernel_branch() {
  case "$1" in
    6.1) echo "develop-6.1" ;;
    6.6) echo "develop-6.6" ;;
    *) echo "Error: Invalid kernel version $1. Supported: 6.1, 6.6" >&2; exit 1 ;;
  esac
}

# Validate profile
validate_profile() {
  local profile="$1"
  if [[ ! -v KERNEL_PROFILES[$profile] ]]; then
    echo "Error: Invalid build profile '$profile'" >&2
    echo "Available profiles: ${!KERNEL_PROFILES[@]}" >&2
    exit 1
  fi
}
